import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, BarChart3, Check, ChevronDown, CircleCheck, ListChecks, MapPin, Menu, Search, ShoppingBasket, Sparkles, Store, X } from 'lucide-react'

const shopperSteps = [
  { icon: Search, title: 'Encontre sem rodar a loja', text: 'Busque por produto, marca ou categoria e veja preço, oferta e disponibilidade.' },
  { icon: MapPin, title: 'Saiba exatamente onde ir', text: 'Localize o departamento e transforme a lista em um percurso mais simples.' },
  { icon: ListChecks, title: 'Compre com o total à vista', text: 'Monte sua lista, acompanhe os itens e veja o valor estimado antes do caixa.' },
]
const signals = ['Buscas e produtos visualizados', 'Itens adicionados à lista', 'Ofertas que despertam interesse', 'Produtos procurados e não encontrados']

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  return (
    <div className="landing-page">
      <header className="landing-nav">
        <a className="brand" href="#inicio" aria-label="Auxiliador de Compras — início"><span className="brand-mark"><ShoppingBasket size={21} /></span><span>auxiliador<span>.</span></span></a>
        <nav className={menuOpen ? 'nav-links open' : 'nav-links'} aria-label="Navegação principal">
          <a href="#produto" onClick={() => setMenuOpen(false)}>Produto</a><a href="#varejo" onClick={() => setMenuOpen(false)}>Para supermercados</a><a href="#piloto" onClick={() => setMenuOpen(false)}>Piloto</a><Link to="/app" onClick={() => setMenuOpen(false)}>Área do cliente</Link><a className="nav-cta" href="#conversa" onClick={() => setMenuOpen(false)}>Quero conhecer <ArrowRight size={16} /></a>
        </nav>
        <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'}>{menuOpen ? <X /> : <Menu />}</button>
      </header>
      <main>
        <section id="inicio" className="hero-section">
          <div className="hero-glow" />
          <div className="hero-copy"><div className="eyebrow"><Sparkles size={15} /> A camada digital da loja física</div><h1>Seu cliente encontra.<br /><em>Sua loja entende.</em></h1><p>Uma experiência de compra que ajuda o consumidor dentro do supermercado e revela, com privacidade, onde existe intenção, interesse e demanda não atendida.</p><div className="hero-actions"><a className="button primary" href="#conversa">Conversar sobre um piloto <ArrowRight size={18} /></a><Link className="button ghost" to="/app">Explorar o Shopper</Link></div><div className="hero-proof"><CircleCheck size={17} /> Feito para supermercados independentes e redes regionais</div></div>
          <div className="hero-visual" aria-label="Prévia da experiência do consumidor">
            <div className="phone-card"><div className="phone-top"><span>Olá, Marina</span><span className="avatar">M</span></div><div className="store-pill"><Store size={15} /> Mercado Central · Loja Centro <ChevronDown size={14} /></div><div className="search-box"><Search size={18} /> Buscar produto, marca ou categoria</div><div className="phone-title"><span>Sua lista</span><small>4 de 7 itens</small></div><div className="list-item checked"><span><Check size={14} /></span><div><strong>Arroz integral</strong><small>Corredor 3 · Prateleira B</small></div><b>R$ 8,90</b></div><div className="list-item checked"><span><Check size={14} /></span><div><strong>Leite integral</strong><small>Frios · Geladeira 2</small></div><b>R$ 5,49</b></div><div className="list-item"><span /> <div><strong>Café 500g</strong><small>Corredor 5 · Prateleira A</small></div><b>R$ 18,90</b></div><div className="route-card"><MapPin size={17} /><div><small>Próxima parada</small><strong>Corredor 5 · Café</strong></div><ArrowRight size={17} /></div><div className="cart-total"><span>Total estimado<small>7 itens na lista</small></span><strong>R$ 86,42</strong></div></div>
            <div className="floating-note note-one"><Search size={17} /><span><b>12 buscas</b><small>nesta sessão</small></span></div><div className="floating-note note-two"><BarChart3 size={17} /><span><b>Intenção visível</b><small>em dados agregados</small></span></div>
          </div>
        </section>
        <section className="context-strip" aria-label="Participantes da plataforma"><span>Uma plataforma. Três perspectivas.</span><div><b>Shopper</b> compra melhor</div><i /><div><b>Retail</b> entende a jornada</div><i /><div className="future"><b>Ads</b> ativa no contexto <small>futuro</small></div></section>
        <section id="produto" className="section product-section"><div className="section-heading"><span className="section-number">01</span><div><p className="kicker">Auxiliador Shopper</p><h2>Menos procura.<br />Mais compra.</h2></div><p>O consumidor recebe ajuda prática do planejamento ao corredor — gratuitamente e com uma experiência pensada primeiro para o celular.</p></div><div className="feature-grid">{shopperSteps.map(({ icon: Icon, title, text }, index) => <article className="feature-card" key={title}><div className="feature-top"><span>0{index + 1}</span><Icon size={25} /></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
        <section id="varejo" className="retail-section"><div className="retail-copy"><p className="kicker light">Auxiliador Retail</p><h2>O caixa mostra o que saiu.<br /><em>Nós mostramos o que faltou.</em></h2><p>Antes da venda existe uma jornada inteira. Transforme sinais de busca, comparação e lista em decisões melhores de sortimento, oferta e operação.</p><div className="signal-list">{signals.map((signal) => <div key={signal}><Check size={16} /> {signal}</div>)}</div><p className="privacy-note">Dados agregados e consentidos. Sem chamar lista concluída de compra realizada.</p></div><div className="insight-panel"><div className="panel-head"><div><small>Visão da loja</small><strong>Intenção do cliente</strong></div><span>Últimos 7 dias</span></div><div className="metric-row"><div><small>Buscas na loja</small><b>1.284</b></div><div><small>Sem resultado</small><b>8,4%</b></div></div><div className="chart-label"><span>Interesse por categoria</span><small>interações</small></div>{[['Hortifruti', 84], ['Mercearia', 68], ['Frios', 52], ['Higiene', 37]].map(([name, value]) => <div className="bar-row" key={name as string}><span>{name}</span><div><i style={{ width: `${value}%` }} /></div><small>{value}</small></div>)}<div className="missed-card"><span>Oportunidade da semana</span><b>“Leite sem lactose” foi a busca sem resultado mais recorrente.</b></div></div></section>
        <section id="piloto" className="section pilot-section"><div className="pilot-intro"><p className="kicker">Piloto fundador</p><h2>Comece com uma loja.<br />Aprenda com cada jornada.</h2><p>Um ciclo de validação desenhado para descobrir se a experiência gera utilidade ao consumidor e inteligência acionável ao supermercado.</p></div><div className="pilot-flow">{[['01', 'Preparar', 'Organizamos catálogo, preços, posições e ofertas da loja piloto.'], ['02', 'Ativar', 'Colocamos o Shopper nas mãos dos clientes e acompanhamos o uso.'], ['03', 'Aprender', 'Revisamos buscas, listas e fricções para orientar as próximas decisões.']].map(([n, title, text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="pilot-callout"><div><strong>A pergunta que importa</strong><p>Seus clientes usam a experiência — e os sinais gerados ajudam sua loja a decidir melhor?</p></div><a className="button dark" href="#conversa">Vamos validar juntos <ArrowRight size={18} /></a></div></section>
        <section id="conversa" className="contact-section"><div className="contact-copy"><p className="kicker light">Próximo passo</p><h2>Sua loja pode ser<br />o próximo laboratório.</h2><p>Conte um pouco sobre a operação. A conversa inicial serve para avaliar aderência ao piloto — sem promessa pronta, sem apresentação genérica.</p><div className="contact-detail"><Store size={19} /><span><b>Perfil inicial</b>Supermercados independentes e pequenas redes regionais</span></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><div className="field-grid"><label>Seu nome<input required name="nome" placeholder="Como podemos chamar você?" /></label><label>Supermercado<input required name="mercado" placeholder="Nome da operação" /></label></div><div className="field-grid"><label>E-mail profissional<input required type="email" name="email" placeholder="voce@supermercado.com.br" /></label><label>Número de lojas<select name="lojas" defaultValue=""><option value="" disabled>Selecione</option><option>1 loja</option><option>2 a 3 lojas</option><option>4 ou mais lojas</option></select></label></div><label>O que mais dificulta a jornada do seu cliente hoje?<textarea name="desafio" rows={3} placeholder="Conte brevemente o contexto da sua loja" /></label><button className="button lime" type="submit">Solicitar uma conversa <ArrowRight size={18} /></button>{sent && <div className="success-message"><CircleCheck size={18} /> Recebemos seu interesse. Este protótipo não envia dados; conectaremos o canal comercial na próxima etapa.</div>}</form></section>
      </main>
      <footer className="landing-footer"><a className="brand" href="#inicio"><span className="brand-mark"><ShoppingBasket size={20} /></span><span>auxiliador<span>.</span></span></a><p>Experiência para quem compra. Inteligência para quem vende.</p><span>© {new Date().getFullYear()}</span></footer>
    </div>
  )
}
